<a href="https://colab.research.google.com/github/manoj-mathivanan/pythonML/blob/main/Jaro009_Exercise_20240804.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Please upload the completed assignment here:

URL =  https://forms.gle/TKDexYXYvRuK1scS8

Please note that all submissions will receive a confirmation email.





---



---



# Based on Numpy basics



**Q1:** Perform the following tasks:


(a) Create a NumPy array with the following values: [1, 2, 3, 4, 5]

In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]



(b) Compute the square of each element in the array.

In [2]:
squared_arr = arr ** 2
print(squared_arr)

[ 1  4  9 16 25]



(c) Compute the mean of the array.




In [3]:
mean_value = np.mean(arr)
print(mean_value)

3.0


(d) Create a second NumPy array with the values [6, 7, 8, 9, 10].



In [4]:
arr2 = np.array([6, 7, 8, 9, 10])
print(arr2)


[ 6  7  8  9 10]


(e) Concatenate the first and second arrays into a single array.


In [8]:
concatenated_arr = np.concatenate((arr, arr2))
print(concatenated_arr)

[ 1  2  3  4  5  6  7  8  9 10]


(f) Reshape the concatenated array into a 2x5 matrix.


In [14]:
reshaped_matrix = concatenated_arr.reshape(2, 5)
print(reshaped_matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(g) Compute the sum of each column in the 2x5 matrix.

In [17]:
column_sums = reshaped_matrix.sum(axis=0)
print(column_sums)

[ 7  9 11 13 15]


(h) Find the index of the maximum value in the reshaped matrix.

In [18]:
max_index = np.argmax(reshaped_matrix)
print(max_index)

9




---



**Q2:** Perform the following tasks:




(a) Create a NumPy array named "data" with 20 elements randomly generated between 0 and 100 (inclusive). Ensure that the array has a data type of "int".

In [20]:
data = np.random.randint(0, 101, size=20, dtype=int)
print(data)

[ 67  78  81  72  28   7  11  35  96  37  87  51  56  63  54  98  51  76
 100  17]


(b) Reshape this array into a 4x5 matrix.

In [22]:
reshaped_data = data.reshape(4, 5)
print(reshaped_data)

[[ 67  78  81  72  28]
 [  7  11  35  96  37]
 [ 87  51  56  63  54]
 [ 98  51  76 100  17]]


(c) Create a second matrix "mask" of the same shape (4x5) where each element is "True" if the corresponding element in the "data" matrix is greater than 50, and "False" otherwise.

In [24]:
mask = reshaped_data > 50
print(mask)

[[ True  True  True  True False]
 [False False False  True False]
 [ True  True  True  True  True]
 [ True  True  True  True False]]


(d) Use the "mask" matrix to extract all values from the "data" matrix that are greater than 50.

In [26]:
values_above_50 = reshaped_data[mask]
print(values_above_50)

[ 67  78  81  72  96  87  51  56  63  54  98  51  76 100]


(e) Compute the sum of all values in the "data" matrix that are greater than 50.

In [27]:
sum_above_50 = np.sum(values_above_50)
print(sum_above_50)

1030


(f) Compute the standard deviation of the entire "data" matrix.

In [28]:
deviation = np.std(data)
print(deviation)

28.001562456405892


(g) Create a 1D array indices containing the row indices of the maximum value in each column of the data matrix.

In [29]:
indices = np.argmax(reshaped_data, axis=0)
print(indices)

[3 0 0 3 2]


(h) Compute the mean of the values in each row of the "data" matrix.

In [32]:
mean_values = np.mean(reshaped_data, axis=0)
print(mean_values)

[64.75 47.75 62.   82.75 34.  ]


(i) Perform matrix multiplication between the "data" matrix and its transpose. Ensure that the result is stored in a variable named "result".


In [33]:
reshaped_data_T = reshaped_data.T
result = np.dot(reshaped_data, reshaped_data_T)
print(result)

[[23102 12110 20391 24376]
 [12110 11980 11176 14136]
 [20391 11176 20191 22601]
 [24376 14136 22601 28270]]


(j) Normalize each column of the "data" matrix by subtracting the mean of that column and then dividing by the standard deviation of that column. Store the normalized matrix in a variable named "normalized_data".

In [34]:
normalized_data = (reshaped_data - np.mean(reshaped_data, axis=0)) / np.std(reshaped_data, axis=0)
print(normalized_data)

[[ 0.06402006  1.26516168  1.04512412 -0.68723073 -0.44292808]
 [-1.64318153 -1.53701461 -1.48517638  0.84705183  0.22146404]
 [ 0.63308726  0.13592646 -0.33003919 -1.26258669  1.47642694]
 [ 0.94607421  0.13592646  0.77009145  1.10276559 -1.2549629 ]]




---



---

